### PR TITLE
more accessible heading-anchors with anchored-heading wrapper divs

### PR DESCRIPTION
**Pull request by rdela**
hopefully achieved more accessible heading-anchors through anchored-heading wrapper divs

see conversation on mastodon at:
https://tweesecake.social/@weirdwriter/112939207207501581 

@rkingett how does this heading anchor implementation stack up? the link is separate from the heading now. I will add a comment with a good demo link momentarily.

Cc @zachleat

### CODE REVIEW

**Comment by rdela** [comment]
Ok @rkingett what about this demo link https://deploy-preview-44--eleventeen.netlify.app/archive/thirdpost/

**Comment by rkingett** [comment]
It would be better if the anchor link wasn't a heading element, [like this preview here](https://deploy-preview-44--eleventeen.netlify.app/archive/thirdpost/) or see below,

https://deploy-preview-44--eleventeen.netlify.app/archive/thirdpost/

**Comment by rdela** [comment]
Thank you @rkingett I really appreciate you taking the time to review this! I will merge these changes from the preview you liked into eleventeen here. Eleventeen is my personal fork of Eleventy Base Blog. We will keep the conversation going about what to do in the upcoming [v9 release of Eleventy Base Blog](https://github.com/11ty/eleventy-base-blog/tree/v9) over there and loop you in if necessary. That is where @zachleat was experimenting and [sent the original preview link from](https://fosstodon.org/@eleventy/112934039098464729).

**Comment by rdela** [comment]
ended up needing to use `data-heading-anchors-optout` in a few more places in #45

**Comment by zachleat** [comment]
Howdy y’all—just following up here with a new approach added to eleventy-base-blog this week: https://github.com/zachleat/heading-anchors

This web component uses anchor links that are siblings and are not nested but also don’t require a wrapper element, which would have complicated styling.

https://github.com/zachleat/heading-anchors

Y’all can see it in action here: https://eleventy-base-blog-git-v9-11ty.vercel.app/blog/thirdpost/

**Comment by rkingett** [comment]
[This demo is perfect](https://eleventy-base-blog-git-v9-11ty.vercel.app/blog/thirdpost/) after the update so I actually consider this resolved!

**Pull request merged**
